// export * from './aa.service';
// import { AaService } from './aa.service';
// export * from './algorithm.service';
// import { AlgorithmService } from './algorithm.service';
// export * from './bibtex.service';
// import { BibtexService } from './bibtex.service';
// export * from './dataset.service';
// import { DatasetService } from './dataset.service';
// export * from './doseresponse.service';
// import { DoseresponseService } from './doseresponse.service';
// export * from './enm.service';
// import { EnmService } from './enm.service';
// export * from './feature.service';
// import { FeatureService } from './feature.service';
// export * from './interlab.service';
// import { InterlabService } from './interlab.service';
// export * from './model.service';
// import { ModelService } from './model.service';
// export * from './openrisknet.service';
// import { OpenrisknetService } from './openrisknet.service';
// export * from './pmml.service';
// import { PmmlService } from './pmml.service';
// export * from './readacross.service';
// import { ReadacrossService } from './readacross.service';
// export * from './report.service';
// import { ReportService } from './report.service';
// export * from './task.service';
// import { TaskService } from './task.service';
// export * from './user.service';
// import { UserService } from './user.service';
// export * from './validation.service';
// import { ValidationService } from './validation.service';
// export const APIS = [AaService, AlgorithmService, BibtexService, DatasetService, DoseresponseService, EnmService, FeatureService, InterlabService, ModelService, OpenrisknetService, PmmlService, ReadacrossService, ReportService, TaskService, UserService, ValidationService];
